/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OsRouteImport } from './routes/os'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSuppliersRouteImport } from './routes/app/suppliers'
import { Route as AppProjectsRouteImport } from './routes/app/projects'
import { Route as AppMaterialsRouteImport } from './routes/app/materials'
import { Route as AppFleetRouteImport } from './routes/app/fleet'
import { Route as AppEmployeesRouteImport } from './routes/app/employees'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppDailyLogRouteImport } from './routes/app/daily-log'

const OsRoute = OsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaterialsRoute = AppMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFleetRoute = AppFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDailyLogRoute = AppDailyLogRouteImport.update({
  id: '/daily-log',
  path: '/daily-log',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/os': typeof OsRoute
  '/app/daily-log': typeof AppDailyLogRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/fleet': typeof AppFleetRoute
  '/app/materials': typeof AppMaterialsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/os': typeof OsRoute
  '/app/daily-log': typeof AppDailyLogRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/fleet': typeof AppFleetRoute
  '/app/materials': typeof AppMaterialsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/os': typeof OsRoute
  '/app/daily-log': typeof AppDailyLogRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/fleet': typeof AppFleetRoute
  '/app/materials': typeof AppMaterialsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/os'
    | '/app/daily-log'
    | '/app/dashboard'
    | '/app/employees'
    | '/app/fleet'
    | '/app/materials'
    | '/app/projects'
    | '/app/suppliers'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/os'
    | '/app/daily-log'
    | '/app/dashboard'
    | '/app/employees'
    | '/app/fleet'
    | '/app/materials'
    | '/app/projects'
    | '/app/suppliers'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/os'
    | '/app/daily-log'
    | '/app/dashboard'
    | '/app/employees'
    | '/app/fleet'
    | '/app/materials'
    | '/app/projects'
    | '/app/suppliers'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  OsRoute: typeof OsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/os': {
      id: '/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof OsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/materials': {
      id: '/app/materials'
      path: '/materials'
      fullPath: '/app/materials'
      preLoaderRoute: typeof AppMaterialsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/fleet': {
      id: '/app/fleet'
      path: '/fleet'
      fullPath: '/app/fleet'
      preLoaderRoute: typeof AppFleetRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/employees': {
      id: '/app/employees'
      path: '/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/daily-log': {
      id: '/app/daily-log'
      path: '/daily-log'
      fullPath: '/app/daily-log'
      preLoaderRoute: typeof AppDailyLogRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDailyLogRoute: typeof AppDailyLogRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppFleetRoute: typeof AppFleetRoute
  AppMaterialsRoute: typeof AppMaterialsRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDailyLogRoute: AppDailyLogRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppFleetRoute: AppFleetRoute,
  AppMaterialsRoute: AppMaterialsRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  OsRoute: OsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
